/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_MessageFrame;
extern struct asn_TYPE_descriptor_s asn_DEF_BasicSafetyMessage;
extern struct asn_TYPE_descriptor_s asn_DEF_PartII_Id;
extern struct asn_TYPE_descriptor_s asn_DEF_CommonSafetyRequest;
extern struct asn_TYPE_descriptor_s asn_DEF_EmergencyVehicleAlert;
extern struct asn_TYPE_descriptor_s asn_DEF_IntersectionCollision;
extern struct asn_TYPE_descriptor_s asn_DEF_MapData;
extern struct asn_TYPE_descriptor_s asn_DEF_NMEAcorrections;
extern struct asn_TYPE_descriptor_s asn_DEF_PersonalSafetyMessage;
extern struct asn_TYPE_descriptor_s asn_DEF_ProbeDataManagement;
extern struct asn_TYPE_descriptor_s asn_DEF_ProbeVehicleData;
extern struct asn_TYPE_descriptor_s asn_DEF_RoadSideAlert;
extern struct asn_TYPE_descriptor_s asn_DEF_RTCMcorrections;
extern struct asn_TYPE_descriptor_s asn_DEF_SPAT;
extern struct asn_TYPE_descriptor_s asn_DEF_SignalRequestMessage;
extern struct asn_TYPE_descriptor_s asn_DEF_SignalStatusMessage;
extern struct asn_TYPE_descriptor_s asn_DEF_TravelerInformation;
extern struct asn_TYPE_descriptor_s asn_DEF_TestMessage00;
extern struct asn_TYPE_descriptor_s asn_DEF_TestMessage01;
extern struct asn_TYPE_descriptor_s asn_DEF_TestMessage02;
extern struct asn_TYPE_descriptor_s asn_DEF_TestMessage03;
extern struct asn_TYPE_descriptor_s asn_DEF_TestMessage04;
extern struct asn_TYPE_descriptor_s asn_DEF_TestMessage05;
extern struct asn_TYPE_descriptor_s asn_DEF_TestMessage06;
extern struct asn_TYPE_descriptor_s asn_DEF_TestMessage07;
extern struct asn_TYPE_descriptor_s asn_DEF_TestMessage08;
extern struct asn_TYPE_descriptor_s asn_DEF_TestMessage09;
extern struct asn_TYPE_descriptor_s asn_DEF_TestMessage10;
extern struct asn_TYPE_descriptor_s asn_DEF_TestMessage11;
extern struct asn_TYPE_descriptor_s asn_DEF_TestMessage12;
extern struct asn_TYPE_descriptor_s asn_DEF_TestMessage13;
extern struct asn_TYPE_descriptor_s asn_DEF_TestMessage14;
extern struct asn_TYPE_descriptor_s asn_DEF_TestMessage15;
extern struct asn_TYPE_descriptor_s asn_DEF_AccelerationSet4Way;
extern struct asn_TYPE_descriptor_s asn_DEF_AccelSteerYawRateConfidence;
extern struct asn_TYPE_descriptor_s asn_DEF_AdvisorySpeed;
extern struct asn_TYPE_descriptor_s asn_DEF_AdvisorySpeedList;
extern struct asn_TYPE_descriptor_s asn_DEF_AntennaOffsetSet;
extern struct asn_TYPE_descriptor_s asn_DEF_ApproachOrLane;
extern struct asn_TYPE_descriptor_s asn_DEF_BrakeSystemStatus;
extern struct asn_TYPE_descriptor_s asn_DEF_BSMcoreData;
extern struct asn_TYPE_descriptor_s asn_DEF_BumperHeights;
extern struct asn_TYPE_descriptor_s asn_DEF_Circle;
extern struct asn_TYPE_descriptor_s asn_DEF_ComputedLane;
extern struct asn_TYPE_descriptor_s asn_DEF_ConfidenceSet;
extern struct asn_TYPE_descriptor_s asn_DEF_ConnectingLane;
extern struct asn_TYPE_descriptor_s asn_DEF_Connection;
extern struct asn_TYPE_descriptor_s asn_DEF_ConnectionManeuverAssist;
extern struct asn_TYPE_descriptor_s asn_DEF_ConnectsToList;
extern struct asn_TYPE_descriptor_s asn_DEF_DataParameters;
extern struct asn_TYPE_descriptor_s asn_DEF_DDate;
extern struct asn_TYPE_descriptor_s asn_DEF_DDateTime;
extern struct asn_TYPE_descriptor_s asn_DEF_DFullTime;
extern struct asn_TYPE_descriptor_s asn_DEF_DMonthDay;
extern struct asn_TYPE_descriptor_s asn_DEF_DTime;
extern struct asn_TYPE_descriptor_s asn_DEF_DYearMonth;
extern struct asn_TYPE_descriptor_s asn_DEF_DisabledVehicle;
extern struct asn_TYPE_descriptor_s asn_DEF_EmergencyDetails;
extern struct asn_TYPE_descriptor_s asn_DEF_EnabledLaneList;
extern struct asn_TYPE_descriptor_s asn_DEF_EventDescription;
extern struct asn_TYPE_descriptor_s asn_DEF_FullPositionVector;
extern struct asn_TYPE_descriptor_s asn_DEF_GenericLane;
extern struct asn_TYPE_descriptor_s asn_DEF_GeographicalPath;
extern struct asn_TYPE_descriptor_s asn_DEF_GeometricProjection;
extern struct asn_TYPE_descriptor_s asn_DEF_Header;
extern struct asn_TYPE_descriptor_s asn_DEF_IntersectionAccessPoint;
extern struct asn_TYPE_descriptor_s asn_DEF_IntersectionGeometry;
extern struct asn_TYPE_descriptor_s asn_DEF_IntersectionGeometryList;
extern struct asn_TYPE_descriptor_s asn_DEF_IntersectionReferenceID;
extern struct asn_TYPE_descriptor_s asn_DEF_IntersectionState;
extern struct asn_TYPE_descriptor_s asn_DEF_IntersectionStateList;
extern struct asn_TYPE_descriptor_s asn_DEF_ExitService;
extern struct asn_TYPE_descriptor_s asn_DEF_GenericSignage;
extern struct asn_TYPE_descriptor_s asn_DEF_SpeedLimit;
extern struct asn_TYPE_descriptor_s asn_DEF_WorkZone;
extern struct asn_TYPE_descriptor_s asn_DEF_J1939data;
extern struct asn_TYPE_descriptor_s asn_DEF_TireDataList;
extern struct asn_TYPE_descriptor_s asn_DEF_TireData;
extern struct asn_TYPE_descriptor_s asn_DEF_AxleWeightList;
extern struct asn_TYPE_descriptor_s asn_DEF_AxleWeightSet;
extern struct asn_TYPE_descriptor_s asn_DEF_LaneAttributes;
extern struct asn_TYPE_descriptor_s asn_DEF_LaneDataAttribute;
extern struct asn_TYPE_descriptor_s asn_DEF_LaneDataAttributeList;
extern struct asn_TYPE_descriptor_s asn_DEF_LaneList;
extern struct asn_TYPE_descriptor_s asn_DEF_LaneTypeAttributes;
extern struct asn_TYPE_descriptor_s asn_DEF_ManeuverAssistList;
extern struct asn_TYPE_descriptor_s asn_DEF_MovementEventList;
extern struct asn_TYPE_descriptor_s asn_DEF_MovementEvent;
extern struct asn_TYPE_descriptor_s asn_DEF_MovementList;
extern struct asn_TYPE_descriptor_s asn_DEF_MovementState;
extern struct asn_TYPE_descriptor_s asn_DEF_Node_LL_24B;
extern struct asn_TYPE_descriptor_s asn_DEF_Node_LL_28B;
extern struct asn_TYPE_descriptor_s asn_DEF_Node_LL_32B;
extern struct asn_TYPE_descriptor_s asn_DEF_Node_LL_36B;
extern struct asn_TYPE_descriptor_s asn_DEF_Node_LL_44B;
extern struct asn_TYPE_descriptor_s asn_DEF_Node_LL_48B;
extern struct asn_TYPE_descriptor_s asn_DEF_Node_LLmD_64b;
extern struct asn_TYPE_descriptor_s asn_DEF_Node_XY_20b;
extern struct asn_TYPE_descriptor_s asn_DEF_Node_XY_22b;
extern struct asn_TYPE_descriptor_s asn_DEF_Node_XY_24b;
extern struct asn_TYPE_descriptor_s asn_DEF_Node_XY_26b;
extern struct asn_TYPE_descriptor_s asn_DEF_Node_XY_28b;
extern struct asn_TYPE_descriptor_s asn_DEF_Node_XY_32b;
extern struct asn_TYPE_descriptor_s asn_DEF_NodeAttributeLLList;
extern struct asn_TYPE_descriptor_s asn_DEF_NodeAttributeSetLL;
extern struct asn_TYPE_descriptor_s asn_DEF_NodeAttributeSetXY;
extern struct asn_TYPE_descriptor_s asn_DEF_NodeAttributeXYList;
extern struct asn_TYPE_descriptor_s asn_DEF_NodeListLL;
extern struct asn_TYPE_descriptor_s asn_DEF_NodeListXY;
extern struct asn_TYPE_descriptor_s asn_DEF_NodeLL;
extern struct asn_TYPE_descriptor_s asn_DEF_NodeOffsetPointLL;
extern struct asn_TYPE_descriptor_s asn_DEF_NodeOffsetPointXY;
extern struct asn_TYPE_descriptor_s asn_DEF_NodeSetLL;
extern struct asn_TYPE_descriptor_s asn_DEF_NodeSetXY;
extern struct asn_TYPE_descriptor_s asn_DEF_NodeXY;
extern struct asn_TYPE_descriptor_s asn_DEF_ObstacleDetection;
extern struct asn_TYPE_descriptor_s asn_DEF_OffsetSystem;
extern struct asn_TYPE_descriptor_s asn_DEF_OverlayLaneList;
extern struct asn_TYPE_descriptor_s asn_DEF_PathHistory;
extern struct asn_TYPE_descriptor_s asn_DEF_PathHistoryPointList;
extern struct asn_TYPE_descriptor_s asn_DEF_PathHistoryPoint;
extern struct asn_TYPE_descriptor_s asn_DEF_PathPrediction;
extern struct asn_TYPE_descriptor_s asn_DEF_PivotPointDescription;
extern struct asn_TYPE_descriptor_s asn_DEF_Position3D;
extern struct asn_TYPE_descriptor_s asn_DEF_PositionalAccuracy;
extern struct asn_TYPE_descriptor_s asn_DEF_PositionConfidenceSet;
extern struct asn_TYPE_descriptor_s asn_DEF_PreemptPriorityList;
extern struct asn_TYPE_descriptor_s asn_DEF_SignalControlZone;
extern struct asn_TYPE_descriptor_s asn_DEF_PrivilegedEvents;
extern struct asn_TYPE_descriptor_s asn_DEF_PropelledInformation;
extern struct asn_TYPE_descriptor_s asn_DEF_RegionList;
extern struct asn_TYPE_descriptor_s asn_DEF_RegionOffsets;
extern struct asn_TYPE_descriptor_s asn_DEF_RegionPointSet;
extern struct asn_TYPE_descriptor_s asn_DEF_RegulatorySpeedLimit;
extern struct asn_TYPE_descriptor_s asn_DEF_RequestedItemList;
extern struct asn_TYPE_descriptor_s asn_DEF_RequestorDescription;
extern struct asn_TYPE_descriptor_s asn_DEF_RequestorPositionVector;
extern struct asn_TYPE_descriptor_s asn_DEF_RequestorType;
extern struct asn_TYPE_descriptor_s asn_DEF_RestrictionClassAssignment;
extern struct asn_TYPE_descriptor_s asn_DEF_RestrictionClassList;
extern struct asn_TYPE_descriptor_s asn_DEF_RestrictionUserTypeList;
extern struct asn_TYPE_descriptor_s asn_DEF_RestrictionUserType;
extern struct asn_TYPE_descriptor_s asn_DEF_RoadLaneSetList;
extern struct asn_TYPE_descriptor_s asn_DEF_RoadSegmentList;
extern struct asn_TYPE_descriptor_s asn_DEF_RoadSegmentReferenceID;
extern struct asn_TYPE_descriptor_s asn_DEF_RoadSegment;
extern struct asn_TYPE_descriptor_s asn_DEF_RoadSignID;
extern struct asn_TYPE_descriptor_s asn_DEF_RTCMheader;
extern struct asn_TYPE_descriptor_s asn_DEF_RTCMmessageList;
extern struct asn_TYPE_descriptor_s asn_DEF_RTCMPackage;
extern struct asn_TYPE_descriptor_s asn_DEF_Sample;
extern struct asn_TYPE_descriptor_s asn_DEF_SegmentAttributeLLList;
extern struct asn_TYPE_descriptor_s asn_DEF_SegmentAttributeXYList;
extern struct asn_TYPE_descriptor_s asn_DEF_ShapePointSet;
extern struct asn_TYPE_descriptor_s asn_DEF_SignalRequesterInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_SignalRequestList;
extern struct asn_TYPE_descriptor_s asn_DEF_SignalRequestPackage;
extern struct asn_TYPE_descriptor_s asn_DEF_SignalRequest;
extern struct asn_TYPE_descriptor_s asn_DEF_SignalStatusList;
extern struct asn_TYPE_descriptor_s asn_DEF_SignalStatusPackageList;
extern struct asn_TYPE_descriptor_s asn_DEF_SignalStatusPackage;
extern struct asn_TYPE_descriptor_s asn_DEF_SignalStatus;
extern struct asn_TYPE_descriptor_s asn_DEF_SnapshotDistance;
extern struct asn_TYPE_descriptor_s asn_DEF_Snapshot;
extern struct asn_TYPE_descriptor_s asn_DEF_SnapshotTime;
extern struct asn_TYPE_descriptor_s asn_DEF_SpecialVehicleExtensions;
extern struct asn_TYPE_descriptor_s asn_DEF_SpeedandHeadingandThrottleConfidence;
extern struct asn_TYPE_descriptor_s asn_DEF_SpeedLimitList;
extern struct asn_TYPE_descriptor_s asn_DEF_SpeedProfileMeasurementList;
extern struct asn_TYPE_descriptor_s asn_DEF_SpeedProfile;
extern struct asn_TYPE_descriptor_s asn_DEF_SupplementalVehicleExtensions;
extern struct asn_TYPE_descriptor_s asn_DEF_TimeChangeDetails;
extern struct asn_TYPE_descriptor_s asn_DEF_TrailerData;
extern struct asn_TYPE_descriptor_s asn_DEF_TrailerHistoryPointList;
extern struct asn_TYPE_descriptor_s asn_DEF_TrailerHistoryPoint;
extern struct asn_TYPE_descriptor_s asn_DEF_TrailerUnitDescriptionList;
extern struct asn_TYPE_descriptor_s asn_DEF_TrailerUnitDescription;
extern struct asn_TYPE_descriptor_s asn_DEF_TransmissionAndSpeed;
extern struct asn_TYPE_descriptor_s asn_DEF_TravelerDataFrameList;
extern struct asn_TYPE_descriptor_s asn_DEF_TravelerDataFrame;
extern struct asn_TYPE_descriptor_s asn_DEF_ValidRegion;
extern struct asn_TYPE_descriptor_s asn_DEF_VehicleClassification;
extern struct asn_TYPE_descriptor_s asn_DEF_VehicleData;
extern struct asn_TYPE_descriptor_s asn_DEF_VehicleIdent;
extern struct asn_TYPE_descriptor_s asn_DEF_VehicleID;
extern struct asn_TYPE_descriptor_s asn_DEF_VehicleSafetyExtensions;
extern struct asn_TYPE_descriptor_s asn_DEF_VehicleSize;
extern struct asn_TYPE_descriptor_s asn_DEF_VehicleStatusRequest;
extern struct asn_TYPE_descriptor_s asn_DEF_VehicleStatusRequestList;
extern struct asn_TYPE_descriptor_s asn_DEF_VehicleStatus;
extern struct asn_TYPE_descriptor_s asn_DEF_VerticalOffset;
extern struct asn_TYPE_descriptor_s asn_DEF_WeatherProbe;
extern struct asn_TYPE_descriptor_s asn_DEF_WeatherReport;
extern struct asn_TYPE_descriptor_s asn_DEF_WiperSet;
extern struct asn_TYPE_descriptor_s asn_DEF_Acceleration;
extern struct asn_TYPE_descriptor_s asn_DEF_AccelerationConfidence;
extern struct asn_TYPE_descriptor_s asn_DEF_AdvisorySpeedType;
extern struct asn_TYPE_descriptor_s asn_DEF_AllowedManeuvers;
extern struct asn_TYPE_descriptor_s asn_DEF_AmbientAirPressure;
extern struct asn_TYPE_descriptor_s asn_DEF_AmbientAirTemperature;
extern struct asn_TYPE_descriptor_s asn_DEF_DSRC_Angle;
extern struct asn_TYPE_descriptor_s asn_DEF_AnimalPropelledType;
extern struct asn_TYPE_descriptor_s asn_DEF_AnimalType;
extern struct asn_TYPE_descriptor_s asn_DEF_AntiLockBrakeStatus;
extern struct asn_TYPE_descriptor_s asn_DEF_ApproachID;
extern struct asn_TYPE_descriptor_s asn_DEF_Attachment;
extern struct asn_TYPE_descriptor_s asn_DEF_AttachmentRadius;
extern struct asn_TYPE_descriptor_s asn_DEF_AuxiliaryBrakeStatus;
extern struct asn_TYPE_descriptor_s asn_DEF_BasicVehicleClass;
extern struct asn_TYPE_descriptor_s asn_DEF_BasicVehicleRole;
extern struct asn_TYPE_descriptor_s asn_DEF_BrakeAppliedPressure;
extern struct asn_TYPE_descriptor_s asn_DEF_BrakeAppliedStatus;
extern struct asn_TYPE_descriptor_s asn_DEF_BrakeBoostApplied;
extern struct asn_TYPE_descriptor_s asn_DEF_BumperHeight;
extern struct asn_TYPE_descriptor_s asn_DEF_CoarseHeading;
extern struct asn_TYPE_descriptor_s asn_DEF_CodeWord;
extern struct asn_TYPE_descriptor_s asn_DEF_CoefficientOfFriction;
extern struct asn_TYPE_descriptor_s asn_DEF_Confidence;
extern struct asn_TYPE_descriptor_s asn_DEF_Count;
extern struct asn_TYPE_descriptor_s asn_DEF_DDay;
extern struct asn_TYPE_descriptor_s asn_DEF_DeltaAngle;
extern struct asn_TYPE_descriptor_s asn_DEF_DeltaTime;
extern struct asn_TYPE_descriptor_s asn_DEF_DescriptiveName;
extern struct asn_TYPE_descriptor_s asn_DEF_DHour;
extern struct asn_TYPE_descriptor_s asn_DEF_DirectionOfUse;
extern struct asn_TYPE_descriptor_s asn_DEF_DistanceUnits;
extern struct asn_TYPE_descriptor_s asn_DEF_DMinute;
extern struct asn_TYPE_descriptor_s asn_DEF_DMonth;
extern struct asn_TYPE_descriptor_s asn_DEF_DOffset;
extern struct asn_TYPE_descriptor_s asn_DEF_DrivenLineOffsetLg;
extern struct asn_TYPE_descriptor_s asn_DEF_DrivenLineOffsetSm;
extern struct asn_TYPE_descriptor_s asn_DEF_DrivingWheelAngle;
extern struct asn_TYPE_descriptor_s asn_DEF_DSecond;
extern struct asn_TYPE_descriptor_s asn_DEF_DSRCmsgID;
extern struct asn_TYPE_descriptor_s asn_DEF_Duration;
extern struct asn_TYPE_descriptor_s asn_DEF_DYear;
extern struct asn_TYPE_descriptor_s asn_DEF_ElevationConfidence;
extern struct asn_TYPE_descriptor_s asn_DEF_DSRC_Elevation;
extern struct asn_TYPE_descriptor_s asn_DEF_Extent;
extern struct asn_TYPE_descriptor_s asn_DEF_ExteriorLights;
extern struct asn_TYPE_descriptor_s asn_DEF_FuelType;
extern struct asn_TYPE_descriptor_s asn_DEF_FurtherInfoID;
extern struct asn_TYPE_descriptor_s asn_DEF_GNSSstatus;
extern struct asn_TYPE_descriptor_s asn_DEF_GrossDistance;
extern struct asn_TYPE_descriptor_s asn_DEF_GrossSpeed;
extern struct asn_TYPE_descriptor_s asn_DEF_HeadingConfidence;
extern struct asn_TYPE_descriptor_s asn_DEF_Heading;
extern struct asn_TYPE_descriptor_s asn_DEF_HeadingSlice;
extern struct asn_TYPE_descriptor_s asn_DEF_IntersectionID;
extern struct asn_TYPE_descriptor_s asn_DEF_IntersectionStatusObject;
extern struct asn_TYPE_descriptor_s asn_DEF_IsDolly;
extern struct asn_TYPE_descriptor_s asn_DEF_Iso3833VehicleType;
extern struct asn_TYPE_descriptor_s asn_DEF_ITIStextPhrase;
extern struct asn_TYPE_descriptor_s asn_DEF_AxleLocation;
extern struct asn_TYPE_descriptor_s asn_DEF_AxleWeight;
extern struct asn_TYPE_descriptor_s asn_DEF_CargoWeight;
extern struct asn_TYPE_descriptor_s asn_DEF_DriveAxleLiftAirPressure;
extern struct asn_TYPE_descriptor_s asn_DEF_DriveAxleLocation;
extern struct asn_TYPE_descriptor_s asn_DEF_DriveAxleLubePressure;
extern struct asn_TYPE_descriptor_s asn_DEF_DriveAxleTemperature;
extern struct asn_TYPE_descriptor_s asn_DEF_SteeringAxleLubePressure;
extern struct asn_TYPE_descriptor_s asn_DEF_SteeringAxleTemperature;
extern struct asn_TYPE_descriptor_s asn_DEF_TireLeakageRate;
extern struct asn_TYPE_descriptor_s asn_DEF_TireLocation;
extern struct asn_TYPE_descriptor_s asn_DEF_TirePressureThresholdDetection;
extern struct asn_TYPE_descriptor_s asn_DEF_TirePressure;
extern struct asn_TYPE_descriptor_s asn_DEF_TireTemp;
extern struct asn_TYPE_descriptor_s asn_DEF_TrailerWeight;
extern struct asn_TYPE_descriptor_s asn_DEF_WheelEndElectFault;
extern struct asn_TYPE_descriptor_s asn_DEF_WheelSensorStatus;
extern struct asn_TYPE_descriptor_s asn_DEF_LaneAttributes_Barrier;
extern struct asn_TYPE_descriptor_s asn_DEF_LaneAttributes_Bike;
extern struct asn_TYPE_descriptor_s asn_DEF_LaneAttributes_Crosswalk;
extern struct asn_TYPE_descriptor_s asn_DEF_LaneAttributes_Parking;
extern struct asn_TYPE_descriptor_s asn_DEF_LaneAttributes_Sidewalk;
extern struct asn_TYPE_descriptor_s asn_DEF_LaneAttributes_Striping;
extern struct asn_TYPE_descriptor_s asn_DEF_LaneAttributes_TrackedVehicle;
extern struct asn_TYPE_descriptor_s asn_DEF_LaneAttributes_Vehicle;
extern struct asn_TYPE_descriptor_s asn_DEF_LaneConnectionID;
extern struct asn_TYPE_descriptor_s asn_DEF_LaneDirection;
extern struct asn_TYPE_descriptor_s asn_DEF_LaneID;
extern struct asn_TYPE_descriptor_s asn_DEF_LaneSharing;
extern struct asn_TYPE_descriptor_s asn_DEF_LaneWidth;
extern struct asn_TYPE_descriptor_s asn_DEF_Latitude;
extern struct asn_TYPE_descriptor_s asn_DEF_LayerID;
extern struct asn_TYPE_descriptor_s asn_DEF_LayerType;
extern struct asn_TYPE_descriptor_s asn_DEF_LightbarInUse;
extern struct asn_TYPE_descriptor_s asn_DEF_Longitude;
extern struct asn_TYPE_descriptor_s asn_DEF_Location_quality;
extern struct asn_TYPE_descriptor_s asn_DEF_Location_tech;
extern struct asn_TYPE_descriptor_s asn_DEF_MergeDivergeNodeAngle;
extern struct asn_TYPE_descriptor_s asn_DEF_MessageBLOB;
extern struct asn_TYPE_descriptor_s asn_DEF_MinuteOfTheYear;
extern struct asn_TYPE_descriptor_s asn_DEF_MinutesDuration;
extern struct asn_TYPE_descriptor_s asn_DEF_MotorizedPropelledType;
extern struct asn_TYPE_descriptor_s asn_DEF_MovementPhaseState;
extern struct asn_TYPE_descriptor_s asn_DEF_DSRC_MsgCount;
extern struct asn_TYPE_descriptor_s asn_DEF_MsgCRC;
extern struct asn_TYPE_descriptor_s asn_DEF_MultiVehicleResponse;
extern struct asn_TYPE_descriptor_s asn_DEF_MUTCDCode;
extern struct asn_TYPE_descriptor_s asn_DEF_NMEA_MsgType;
extern struct asn_TYPE_descriptor_s asn_DEF_NMEA_Payload;
extern struct asn_TYPE_descriptor_s asn_DEF_NMEA_Revision;
extern struct asn_TYPE_descriptor_s asn_DEF_NodeAttributeLL;
extern struct asn_TYPE_descriptor_s asn_DEF_NodeAttributeXY;
extern struct asn_TYPE_descriptor_s asn_DEF_NumberOfParticipantsInCluster;
extern struct asn_TYPE_descriptor_s asn_DEF_ObjectCount;
extern struct asn_TYPE_descriptor_s asn_DEF_ObstacleDirection;
extern struct asn_TYPE_descriptor_s asn_DEF_ObstacleDistance;
extern struct asn_TYPE_descriptor_s asn_DEF_Offset_B09;
extern struct asn_TYPE_descriptor_s asn_DEF_Offset_B10;
extern struct asn_TYPE_descriptor_s asn_DEF_Offset_B11;
extern struct asn_TYPE_descriptor_s asn_DEF_Offset_B12;
extern struct asn_TYPE_descriptor_s asn_DEF_Offset_B13;
extern struct asn_TYPE_descriptor_s asn_DEF_Offset_B14;
extern struct asn_TYPE_descriptor_s asn_DEF_Offset_B16;
extern struct asn_TYPE_descriptor_s asn_DEF_OffsetLL_B12;
extern struct asn_TYPE_descriptor_s asn_DEF_OffsetLL_B14;
extern struct asn_TYPE_descriptor_s asn_DEF_OffsetLL_B16;
extern struct asn_TYPE_descriptor_s asn_DEF_OffsetLL_B18;
extern struct asn_TYPE_descriptor_s asn_DEF_OffsetLL_B22;
extern struct asn_TYPE_descriptor_s asn_DEF_OffsetLL_B24;
extern struct asn_TYPE_descriptor_s asn_DEF_PayloadData;
extern struct asn_TYPE_descriptor_s asn_DEF_PedestrianBicycleDetect;
extern struct asn_TYPE_descriptor_s asn_DEF_HumanPropelledType;
extern struct asn_TYPE_descriptor_s asn_DEF_PersonalAssistive;
extern struct asn_TYPE_descriptor_s asn_DEF_PersonalClusterRadius;
extern struct asn_TYPE_descriptor_s asn_DEF_PersonalCrossingInProgress;
extern struct asn_TYPE_descriptor_s asn_DEF_PersonalCrossingRequest;
extern struct asn_TYPE_descriptor_s asn_DEF_PersonalDeviceUsageState;
extern struct asn_TYPE_descriptor_s asn_DEF_PersonalDeviceUserType;
extern struct asn_TYPE_descriptor_s asn_DEF_PivotingAllowed;
extern struct asn_TYPE_descriptor_s asn_DEF_PositionConfidence;
extern struct asn_TYPE_descriptor_s asn_DEF_PrioritizationResponseStatus;
extern struct asn_TYPE_descriptor_s asn_DEF_Priority;
extern struct asn_TYPE_descriptor_s asn_DEF_PriorityRequestType;
extern struct asn_TYPE_descriptor_s asn_DEF_PrivilegedEventFlags;
extern struct asn_TYPE_descriptor_s asn_DEF_ProbeSegmentNumber;
extern struct asn_TYPE_descriptor_s asn_DEF_PublicSafetyAndRoadWorkerActivity;
extern struct asn_TYPE_descriptor_s asn_DEF_PublicSafetyDirectingTrafficSubType;
extern struct asn_TYPE_descriptor_s asn_DEF_PublicSafetyEventResponderWorkerType;
extern struct asn_TYPE_descriptor_s asn_DEF_RadiusOfCurvature;
extern struct asn_TYPE_descriptor_s asn_DEF_Radius_B12;
extern struct asn_TYPE_descriptor_s asn_DEF_RainSensor;
extern struct asn_TYPE_descriptor_s asn_DEF_RegionId;
extern struct asn_TYPE_descriptor_s asn_DEF_RequestedItem;
extern struct asn_TYPE_descriptor_s asn_DEF_RequestID;
extern struct asn_TYPE_descriptor_s asn_DEF_RequestImportanceLevel;
extern struct asn_TYPE_descriptor_s asn_DEF_RequestSubRole;
extern struct asn_TYPE_descriptor_s asn_DEF_ResponseType;
extern struct asn_TYPE_descriptor_s asn_DEF_RestrictionAppliesTo;
extern struct asn_TYPE_descriptor_s asn_DEF_RestrictionClassID;
extern struct asn_TYPE_descriptor_s asn_DEF_RoadRegulatorID;
extern struct asn_TYPE_descriptor_s asn_DEF_RoadSegmentID;
extern struct asn_TYPE_descriptor_s asn_DEF_RoadwayCrownAngle;
extern struct asn_TYPE_descriptor_s asn_DEF_RTCM_Revision;
extern struct asn_TYPE_descriptor_s asn_DEF_RTCMmessage;
extern struct asn_TYPE_descriptor_s asn_DEF_Scale_B12;
extern struct asn_TYPE_descriptor_s asn_DEF_SecondOfTime;
extern struct asn_TYPE_descriptor_s asn_DEF_SegmentAttributeLL;
extern struct asn_TYPE_descriptor_s asn_DEF_SegmentAttributeXY;
extern struct asn_TYPE_descriptor_s asn_DEF_SemiMajorAxisAccuracy;
extern struct asn_TYPE_descriptor_s asn_DEF_SemiMajorAxisOrientation;
extern struct asn_TYPE_descriptor_s asn_DEF_SemiMinorAxisAccuracy;
extern struct asn_TYPE_descriptor_s asn_DEF_SignalGroupID;
extern struct asn_TYPE_descriptor_s asn_DEF_SignalReqScheme;
extern struct asn_TYPE_descriptor_s asn_DEF_SignPrority;
extern struct asn_TYPE_descriptor_s asn_DEF_SirenInUse;
extern struct asn_TYPE_descriptor_s asn_DEF_SpeedAdvice;
extern struct asn_TYPE_descriptor_s asn_DEF_SpeedConfidence;
extern struct asn_TYPE_descriptor_s asn_DEF_SpeedLimitType;
extern struct asn_TYPE_descriptor_s asn_DEF_SpeedProfileMeasurement;
extern struct asn_TYPE_descriptor_s asn_DEF_Speed;
extern struct asn_TYPE_descriptor_s asn_DEF_SSPindex;
extern struct asn_TYPE_descriptor_s asn_DEF_StabilityControlStatus;
extern struct asn_TYPE_descriptor_s asn_DEF_StationID;
extern struct asn_TYPE_descriptor_s asn_DEF_SteeringWheelAngleConfidence;
extern struct asn_TYPE_descriptor_s asn_DEF_SteeringWheelAngleRateOfChange;
extern struct asn_TYPE_descriptor_s asn_DEF_SteeringWheelAngle;
extern struct asn_TYPE_descriptor_s asn_DEF_SunSensor;
extern struct asn_TYPE_descriptor_s asn_DEF_TemporaryID;
extern struct asn_TYPE_descriptor_s asn_DEF_TermDistance;
extern struct asn_TYPE_descriptor_s asn_DEF_TermTime;
extern struct asn_TYPE_descriptor_s asn_DEF_ThrottleConfidence;
extern struct asn_TYPE_descriptor_s asn_DEF_ThrottlePosition;
extern struct asn_TYPE_descriptor_s asn_DEF_TimeConfidence;
extern struct asn_TYPE_descriptor_s asn_DEF_TimeIntervalConfidence;
extern struct asn_TYPE_descriptor_s asn_DEF_DSRC_TimeMark;
extern struct asn_TYPE_descriptor_s asn_DEF_TimeOffset;
extern struct asn_TYPE_descriptor_s asn_DEF_TractionControlStatus;
extern struct asn_TYPE_descriptor_s asn_DEF_TrailerMass;
extern struct asn_TYPE_descriptor_s asn_DEF_TransitStatus;
extern struct asn_TYPE_descriptor_s asn_DEF_TransitVehicleOccupancy;
extern struct asn_TYPE_descriptor_s asn_DEF_TransitVehicleStatus;
extern struct asn_TYPE_descriptor_s asn_DEF_TransmissionState;
extern struct asn_TYPE_descriptor_s asn_DEF_TravelerInfoType;
extern struct asn_TYPE_descriptor_s asn_DEF_UniqueMSGID;
extern struct asn_TYPE_descriptor_s asn_DEF_URL_Base;
extern struct asn_TYPE_descriptor_s asn_DEF_URL_Link;
extern struct asn_TYPE_descriptor_s asn_DEF_URL_Short;
extern struct asn_TYPE_descriptor_s asn_DEF_UserSizeAndBehaviour;
extern struct asn_TYPE_descriptor_s asn_DEF_VehicleEventFlags;
extern struct asn_TYPE_descriptor_s asn_DEF_VehicleHeight;
extern struct asn_TYPE_descriptor_s asn_DEF_VehicleLength;
extern struct asn_TYPE_descriptor_s asn_DEF_VehicleMass;
extern struct asn_TYPE_descriptor_s asn_DEF_VehicleStatusDeviceTypeTag;
extern struct asn_TYPE_descriptor_s asn_DEF_VehicleType;
extern struct asn_TYPE_descriptor_s asn_DEF_VehicleWidth;
extern struct asn_TYPE_descriptor_s asn_DEF_Velocity;
extern struct asn_TYPE_descriptor_s asn_DEF_VerticalAccelerationThreshold;
extern struct asn_TYPE_descriptor_s asn_DEF_VerticalAcceleration;
extern struct asn_TYPE_descriptor_s asn_DEF_VertOffset_B07;
extern struct asn_TYPE_descriptor_s asn_DEF_VertOffset_B08;
extern struct asn_TYPE_descriptor_s asn_DEF_VertOffset_B09;
extern struct asn_TYPE_descriptor_s asn_DEF_VertOffset_B10;
extern struct asn_TYPE_descriptor_s asn_DEF_VertOffset_B11;
extern struct asn_TYPE_descriptor_s asn_DEF_VertOffset_B12;
extern struct asn_TYPE_descriptor_s asn_DEF_VINstring;
extern struct asn_TYPE_descriptor_s asn_DEF_WaitOnStopline;
extern struct asn_TYPE_descriptor_s asn_DEF_WiperRate;
extern struct asn_TYPE_descriptor_s asn_DEF_WiperStatus;
extern struct asn_TYPE_descriptor_s asn_DEF_YawRateConfidence;
extern struct asn_TYPE_descriptor_s asn_DEF_YawRate;
extern struct asn_TYPE_descriptor_s asn_DEF_ZoneLength;
extern struct asn_TYPE_descriptor_s asn_DEF_Zoom;
extern struct asn_TYPE_descriptor_s asn_DEF_AltitudeConfidence;
extern struct asn_TYPE_descriptor_s asn_DEF_AltitudeValue;
extern struct asn_TYPE_descriptor_s asn_DEF_EmissionType;
extern struct asn_TYPE_descriptor_s asn_DEF_Altitude;
extern struct asn_TYPE_descriptor_s asn_DEF_PrioritizationResponse;
extern struct asn_TYPE_descriptor_s asn_DEF_PrioritizationResponseList;
extern struct asn_TYPE_descriptor_s asn_DEF_ConnectionManeuverAssist_addGrpC;
extern struct asn_TYPE_descriptor_s asn_DEF_IntersectionState_addGrpC;
extern struct asn_TYPE_descriptor_s asn_DEF_MapData_addGrpC;
extern struct asn_TYPE_descriptor_s asn_DEF_Position3D_addGrpC;
extern struct asn_TYPE_descriptor_s asn_DEF_RestrictionUserType_addGrpC;
extern struct asn_TYPE_descriptor_s asn_DEF_SignalHeadLocation;
extern struct asn_TYPE_descriptor_s asn_DEF_SignalHeadLocationList;
extern struct asn_TYPE_descriptor_s asn_DEF_VehicleToLanePosition;
extern struct asn_TYPE_descriptor_s asn_DEF_VehicleToLanePositionList;
extern struct asn_TYPE_descriptor_s asn_DEF_AddGrpB_Angle;
extern struct asn_TYPE_descriptor_s asn_DEF_Day;
extern struct asn_TYPE_descriptor_s asn_DEF_DayOfWeek;
extern struct asn_TYPE_descriptor_s asn_DEF_DegreesLat;
extern struct asn_TYPE_descriptor_s asn_DEF_DegreesLong;
extern struct asn_TYPE_descriptor_s asn_DEF_AddGrpB_Elevation;
extern struct asn_TYPE_descriptor_s asn_DEF_Holiday;
extern struct asn_TYPE_descriptor_s asn_DEF_Hour;
extern struct asn_TYPE_descriptor_s asn_DEF_LatitudeDMS;
extern struct asn_TYPE_descriptor_s asn_DEF_LongitudeDMS;
extern struct asn_TYPE_descriptor_s asn_DEF_MaxTimetoChange;
extern struct asn_TYPE_descriptor_s asn_DEF_MinTimetoChange;
extern struct asn_TYPE_descriptor_s asn_DEF_Minute;
extern struct asn_TYPE_descriptor_s asn_DEF_MinutesAngle;
extern struct asn_TYPE_descriptor_s asn_DEF_Month;
extern struct asn_TYPE_descriptor_s asn_DEF_AddGrpB_MsgCount;
extern struct asn_TYPE_descriptor_s asn_DEF_Second;
extern struct asn_TYPE_descriptor_s asn_DEF_SecondsAngle;
extern struct asn_TYPE_descriptor_s asn_DEF_SummerTime;
extern struct asn_TYPE_descriptor_s asn_DEF_TenthSecond;
extern struct asn_TYPE_descriptor_s asn_DEF_TimeRemaining;
extern struct asn_TYPE_descriptor_s asn_DEF_Year;
extern struct asn_TYPE_descriptor_s asn_DEF_LatitudeDMS2;
extern struct asn_TYPE_descriptor_s asn_DEF_LongitudeDMS2;
extern struct asn_TYPE_descriptor_s asn_DEF_Node_LLdms_48b;
extern struct asn_TYPE_descriptor_s asn_DEF_Node_LLdms_80b;
extern struct asn_TYPE_descriptor_s asn_DEF_LaneDataAttribute_addGrpB;
extern struct asn_TYPE_descriptor_s asn_DEF_MovementEvent_addGrpB;
extern struct asn_TYPE_descriptor_s asn_DEF_NodeOffsetPointXY_addGrpB;
extern struct asn_TYPE_descriptor_s asn_DEF_Position3D_addGrpB;
extern struct asn_TYPE_descriptor_s asn_DEF_AddGrpB_TimeMark;
extern struct asn_TYPE_descriptor_s asn_DEF_EssMobileFriction;
extern struct asn_TYPE_descriptor_s asn_DEF_EssPrecipRate;
extern struct asn_TYPE_descriptor_s asn_DEF_EssPrecipSituation;
extern struct asn_TYPE_descriptor_s asn_DEF_EssPrecipYesNo;
extern struct asn_TYPE_descriptor_s asn_DEF_EssSolarRadiation;
extern struct asn_TYPE_descriptor_s asn_DEF_GenericLocations;
extern struct asn_TYPE_descriptor_s asn_DEF_IncidentResponseEquipment;
extern struct asn_TYPE_descriptor_s asn_DEF_ITIStext;
extern struct asn_TYPE_descriptor_s asn_DEF_ResponderGroupAffected;
extern struct asn_TYPE_descriptor_s asn_DEF_VehicleGroupAffected;
extern struct asn_TYPE_descriptor_s asn_DEF_ITIScodesAndText;
extern struct asn_TYPE_descriptor_s asn_DEF_ITIScodes;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module DSRC in ../asn/J2735_201603DA.ASN */
	&asn_DEF_MessageFrame,	
	&asn_DEF_BasicSafetyMessage,	
	&asn_DEF_PartII_Id,	
	&asn_DEF_CommonSafetyRequest,	
	&asn_DEF_EmergencyVehicleAlert,	
	&asn_DEF_IntersectionCollision,	
	&asn_DEF_MapData,	
	&asn_DEF_NMEAcorrections,	
	&asn_DEF_PersonalSafetyMessage,	
	&asn_DEF_ProbeDataManagement,	
	&asn_DEF_ProbeVehicleData,	
	&asn_DEF_RoadSideAlert,	
	&asn_DEF_RTCMcorrections,	
	&asn_DEF_SPAT,	
	&asn_DEF_SignalRequestMessage,	
	&asn_DEF_SignalStatusMessage,	
	&asn_DEF_TravelerInformation,	
	&asn_DEF_TestMessage00,	
	&asn_DEF_TestMessage01,	
	&asn_DEF_TestMessage02,	
	&asn_DEF_TestMessage03,	
	&asn_DEF_TestMessage04,	
	&asn_DEF_TestMessage05,	
	&asn_DEF_TestMessage06,	
	&asn_DEF_TestMessage07,	
	&asn_DEF_TestMessage08,	
	&asn_DEF_TestMessage09,	
	&asn_DEF_TestMessage10,	
	&asn_DEF_TestMessage11,	
	&asn_DEF_TestMessage12,	
	&asn_DEF_TestMessage13,	
	&asn_DEF_TestMessage14,	
	&asn_DEF_TestMessage15,	
	&asn_DEF_AccelerationSet4Way,	
	&asn_DEF_AccelSteerYawRateConfidence,	
	&asn_DEF_AdvisorySpeed,	
	&asn_DEF_AdvisorySpeedList,	
	&asn_DEF_AntennaOffsetSet,	
	&asn_DEF_ApproachOrLane,	
	&asn_DEF_BrakeSystemStatus,	
	&asn_DEF_BSMcoreData,	
	&asn_DEF_BumperHeights,	
	&asn_DEF_Circle,	
	&asn_DEF_ComputedLane,	
	&asn_DEF_ConfidenceSet,	
	&asn_DEF_ConnectingLane,	
	&asn_DEF_Connection,	
	&asn_DEF_ConnectionManeuverAssist,	
	&asn_DEF_ConnectsToList,	
	&asn_DEF_DataParameters,	
	&asn_DEF_DDate,	
	&asn_DEF_DDateTime,	
	&asn_DEF_DFullTime,	
	&asn_DEF_DMonthDay,	
	&asn_DEF_DTime,	
	&asn_DEF_DYearMonth,	
	&asn_DEF_DisabledVehicle,	
	&asn_DEF_EmergencyDetails,	
	&asn_DEF_EnabledLaneList,	
	&asn_DEF_EventDescription,	
	&asn_DEF_FullPositionVector,	
	&asn_DEF_GenericLane,	
	&asn_DEF_GeographicalPath,	
	&asn_DEF_GeometricProjection,	
	&asn_DEF_Header,	
	&asn_DEF_IntersectionAccessPoint,	
	&asn_DEF_IntersectionGeometry,	
	&asn_DEF_IntersectionGeometryList,	
	&asn_DEF_IntersectionReferenceID,	
	&asn_DEF_IntersectionState,	
	&asn_DEF_IntersectionStateList,	
	&asn_DEF_ExitService,	
	&asn_DEF_GenericSignage,	
	&asn_DEF_SpeedLimit,	
	&asn_DEF_WorkZone,	
	&asn_DEF_J1939data,	
	&asn_DEF_TireDataList,	
	&asn_DEF_TireData,	
	&asn_DEF_AxleWeightList,	
	&asn_DEF_AxleWeightSet,	
	&asn_DEF_LaneAttributes,	
	&asn_DEF_LaneDataAttribute,	
	&asn_DEF_LaneDataAttributeList,	
	&asn_DEF_LaneList,	
	&asn_DEF_LaneTypeAttributes,	
	&asn_DEF_ManeuverAssistList,	
	&asn_DEF_MovementEventList,	
	&asn_DEF_MovementEvent,	
	&asn_DEF_MovementList,	
	&asn_DEF_MovementState,	
	&asn_DEF_Node_LL_24B,	
	&asn_DEF_Node_LL_28B,	
	&asn_DEF_Node_LL_32B,	
	&asn_DEF_Node_LL_36B,	
	&asn_DEF_Node_LL_44B,	
	&asn_DEF_Node_LL_48B,	
	&asn_DEF_Node_LLmD_64b,	
	&asn_DEF_Node_XY_20b,	
	&asn_DEF_Node_XY_22b,	
	&asn_DEF_Node_XY_24b,	
	&asn_DEF_Node_XY_26b,	
	&asn_DEF_Node_XY_28b,	
	&asn_DEF_Node_XY_32b,	
	&asn_DEF_NodeAttributeLLList,	
	&asn_DEF_NodeAttributeSetLL,	
	&asn_DEF_NodeAttributeSetXY,	
	&asn_DEF_NodeAttributeXYList,	
	&asn_DEF_NodeListLL,	
	&asn_DEF_NodeListXY,	
	&asn_DEF_NodeLL,	
	&asn_DEF_NodeOffsetPointLL,	
	&asn_DEF_NodeOffsetPointXY,	
	&asn_DEF_NodeSetLL,	
	&asn_DEF_NodeSetXY,	
	&asn_DEF_NodeXY,	
	&asn_DEF_ObstacleDetection,	
	&asn_DEF_OffsetSystem,	
	&asn_DEF_OverlayLaneList,	
	&asn_DEF_PathHistory,	
	&asn_DEF_PathHistoryPointList,	
	&asn_DEF_PathHistoryPoint,	
	&asn_DEF_PathPrediction,	
	&asn_DEF_PivotPointDescription,	
	&asn_DEF_Position3D,	
	&asn_DEF_PositionalAccuracy,	
	&asn_DEF_PositionConfidenceSet,	
	&asn_DEF_PreemptPriorityList,	
	&asn_DEF_SignalControlZone,	
	&asn_DEF_PrivilegedEvents,	
	&asn_DEF_PropelledInformation,	
	&asn_DEF_RegionList,	
	&asn_DEF_RegionOffsets,	
	&asn_DEF_RegionPointSet,	
	&asn_DEF_RegulatorySpeedLimit,	
	&asn_DEF_RequestedItemList,	
	&asn_DEF_RequestorDescription,	
	&asn_DEF_RequestorPositionVector,	
	&asn_DEF_RequestorType,	
	&asn_DEF_RestrictionClassAssignment,	
	&asn_DEF_RestrictionClassList,	
	&asn_DEF_RestrictionUserTypeList,	
	&asn_DEF_RestrictionUserType,	
	&asn_DEF_RoadLaneSetList,	
	&asn_DEF_RoadSegmentList,	
	&asn_DEF_RoadSegmentReferenceID,	
	&asn_DEF_RoadSegment,	
	&asn_DEF_RoadSignID,	
	&asn_DEF_RTCMheader,	
	&asn_DEF_RTCMmessageList,	
	&asn_DEF_RTCMPackage,	
	&asn_DEF_Sample,	
	&asn_DEF_SegmentAttributeLLList,	
	&asn_DEF_SegmentAttributeXYList,	
	&asn_DEF_ShapePointSet,	
	&asn_DEF_SignalRequesterInfo,	
	&asn_DEF_SignalRequestList,	
	&asn_DEF_SignalRequestPackage,	
	&asn_DEF_SignalRequest,	
	&asn_DEF_SignalStatusList,	
	&asn_DEF_SignalStatusPackageList,	
	&asn_DEF_SignalStatusPackage,	
	&asn_DEF_SignalStatus,	
	&asn_DEF_SnapshotDistance,	
	&asn_DEF_Snapshot,	
	&asn_DEF_SnapshotTime,	
	&asn_DEF_SpecialVehicleExtensions,	
	&asn_DEF_SpeedandHeadingandThrottleConfidence,	
	&asn_DEF_SpeedLimitList,	
	&asn_DEF_SpeedProfileMeasurementList,	
	&asn_DEF_SpeedProfile,	
	&asn_DEF_SupplementalVehicleExtensions,	
	&asn_DEF_TimeChangeDetails,	
	&asn_DEF_TrailerData,	
	&asn_DEF_TrailerHistoryPointList,	
	&asn_DEF_TrailerHistoryPoint,	
	&asn_DEF_TrailerUnitDescriptionList,	
	&asn_DEF_TrailerUnitDescription,	
	&asn_DEF_TransmissionAndSpeed,	
	&asn_DEF_TravelerDataFrameList,	
	&asn_DEF_TravelerDataFrame,	
	&asn_DEF_ValidRegion,	
	&asn_DEF_VehicleClassification,	
	&asn_DEF_VehicleData,	
	&asn_DEF_VehicleIdent,	
	&asn_DEF_VehicleID,	
	&asn_DEF_VehicleSafetyExtensions,	
	&asn_DEF_VehicleSize,	
	&asn_DEF_VehicleStatusRequest,	
	&asn_DEF_VehicleStatusRequestList,	
	&asn_DEF_VehicleStatus,	
	&asn_DEF_VerticalOffset,	
	&asn_DEF_WeatherProbe,	
	&asn_DEF_WeatherReport,	
	&asn_DEF_WiperSet,	
	&asn_DEF_Acceleration,	
	&asn_DEF_AccelerationConfidence,	
	&asn_DEF_AdvisorySpeedType,	
	&asn_DEF_AllowedManeuvers,	
	&asn_DEF_AmbientAirPressure,	
	&asn_DEF_AmbientAirTemperature,	
	&asn_DEF_DSRC_Angle,	
	&asn_DEF_AnimalPropelledType,	
	&asn_DEF_AnimalType,	
	&asn_DEF_AntiLockBrakeStatus,	
	&asn_DEF_ApproachID,	
	&asn_DEF_Attachment,	
	&asn_DEF_AttachmentRadius,	
	&asn_DEF_AuxiliaryBrakeStatus,	
	&asn_DEF_BasicVehicleClass,	
	&asn_DEF_BasicVehicleRole,	
	&asn_DEF_BrakeAppliedPressure,	
	&asn_DEF_BrakeAppliedStatus,	
	&asn_DEF_BrakeBoostApplied,	
	&asn_DEF_BumperHeight,	
	&asn_DEF_CoarseHeading,	
	&asn_DEF_CodeWord,	
	&asn_DEF_CoefficientOfFriction,	
	&asn_DEF_Confidence,	
	&asn_DEF_Count,	
	&asn_DEF_DDay,	
	&asn_DEF_DeltaAngle,	
	&asn_DEF_DeltaTime,	
	&asn_DEF_DescriptiveName,	
	&asn_DEF_DHour,	
	&asn_DEF_DirectionOfUse,	
	&asn_DEF_DistanceUnits,	
	&asn_DEF_DMinute,	
	&asn_DEF_DMonth,	
	&asn_DEF_DOffset,	
	&asn_DEF_DrivenLineOffsetLg,	
	&asn_DEF_DrivenLineOffsetSm,	
	&asn_DEF_DrivingWheelAngle,	
	&asn_DEF_DSecond,	
	&asn_DEF_DSRCmsgID,	
	&asn_DEF_Duration,	
	&asn_DEF_DYear,	
	&asn_DEF_ElevationConfidence,	
	&asn_DEF_DSRC_Elevation,	
	&asn_DEF_Extent,	
	&asn_DEF_ExteriorLights,	
	&asn_DEF_FuelType,	
	&asn_DEF_FurtherInfoID,	
	&asn_DEF_GNSSstatus,	
	&asn_DEF_GrossDistance,	
	&asn_DEF_GrossSpeed,	
	&asn_DEF_HeadingConfidence,	
	&asn_DEF_Heading,	
	&asn_DEF_HeadingSlice,	
	&asn_DEF_IntersectionID,	
	&asn_DEF_IntersectionStatusObject,	
	&asn_DEF_IsDolly,	
	&asn_DEF_Iso3833VehicleType,	
	&asn_DEF_ITIStextPhrase,	
	&asn_DEF_AxleLocation,	
	&asn_DEF_AxleWeight,	
	&asn_DEF_CargoWeight,	
	&asn_DEF_DriveAxleLiftAirPressure,	
	&asn_DEF_DriveAxleLocation,	
	&asn_DEF_DriveAxleLubePressure,	
	&asn_DEF_DriveAxleTemperature,	
	&asn_DEF_SteeringAxleLubePressure,	
	&asn_DEF_SteeringAxleTemperature,	
	&asn_DEF_TireLeakageRate,	
	&asn_DEF_TireLocation,	
	&asn_DEF_TirePressureThresholdDetection,	
	&asn_DEF_TirePressure,	
	&asn_DEF_TireTemp,	
	&asn_DEF_TrailerWeight,	
	&asn_DEF_WheelEndElectFault,	
	&asn_DEF_WheelSensorStatus,	
	&asn_DEF_LaneAttributes_Barrier,	
	&asn_DEF_LaneAttributes_Bike,	
	&asn_DEF_LaneAttributes_Crosswalk,	
	&asn_DEF_LaneAttributes_Parking,	
	&asn_DEF_LaneAttributes_Sidewalk,	
	&asn_DEF_LaneAttributes_Striping,	
	&asn_DEF_LaneAttributes_TrackedVehicle,	
	&asn_DEF_LaneAttributes_Vehicle,	
	&asn_DEF_LaneConnectionID,	
	&asn_DEF_LaneDirection,	
	&asn_DEF_LaneID,	
	&asn_DEF_LaneSharing,	
	&asn_DEF_LaneWidth,	
	&asn_DEF_Latitude,	
	&asn_DEF_LayerID,	
	&asn_DEF_LayerType,	
	&asn_DEF_LightbarInUse,	
	&asn_DEF_Longitude,	
	&asn_DEF_Location_quality,	
	&asn_DEF_Location_tech,	
	&asn_DEF_MergeDivergeNodeAngle,	
	&asn_DEF_MessageBLOB,	
	&asn_DEF_MinuteOfTheYear,	
	&asn_DEF_MinutesDuration,	
	&asn_DEF_MotorizedPropelledType,	
	&asn_DEF_MovementPhaseState,	
	&asn_DEF_DSRC_MsgCount,	
	&asn_DEF_MsgCRC,	
	&asn_DEF_MultiVehicleResponse,	
	&asn_DEF_MUTCDCode,	
	&asn_DEF_NMEA_MsgType,	
	&asn_DEF_NMEA_Payload,	
	&asn_DEF_NMEA_Revision,	
	&asn_DEF_NodeAttributeLL,	
	&asn_DEF_NodeAttributeXY,	
	&asn_DEF_NumberOfParticipantsInCluster,	
	&asn_DEF_ObjectCount,	
	&asn_DEF_ObstacleDirection,	
	&asn_DEF_ObstacleDistance,	
	&asn_DEF_Offset_B09,	
	&asn_DEF_Offset_B10,	
	&asn_DEF_Offset_B11,	
	&asn_DEF_Offset_B12,	
	&asn_DEF_Offset_B13,	
	&asn_DEF_Offset_B14,	
	&asn_DEF_Offset_B16,	
	&asn_DEF_OffsetLL_B12,	
	&asn_DEF_OffsetLL_B14,	
	&asn_DEF_OffsetLL_B16,	
	&asn_DEF_OffsetLL_B18,	
	&asn_DEF_OffsetLL_B22,	
	&asn_DEF_OffsetLL_B24,	
	&asn_DEF_PayloadData,	
	&asn_DEF_PedestrianBicycleDetect,	
	&asn_DEF_HumanPropelledType,	
	&asn_DEF_PersonalAssistive,	
	&asn_DEF_PersonalClusterRadius,	
	&asn_DEF_PersonalCrossingInProgress,	
	&asn_DEF_PersonalCrossingRequest,	
	&asn_DEF_PersonalDeviceUsageState,	
	&asn_DEF_PersonalDeviceUserType,	
	&asn_DEF_PivotingAllowed,	
	&asn_DEF_PositionConfidence,	
	&asn_DEF_PrioritizationResponseStatus,	
	&asn_DEF_Priority,	
	&asn_DEF_PriorityRequestType,	
	&asn_DEF_PrivilegedEventFlags,	
	&asn_DEF_ProbeSegmentNumber,	
	&asn_DEF_PublicSafetyAndRoadWorkerActivity,	
	&asn_DEF_PublicSafetyDirectingTrafficSubType,	
	&asn_DEF_PublicSafetyEventResponderWorkerType,	
	&asn_DEF_RadiusOfCurvature,	
	&asn_DEF_Radius_B12,	
	&asn_DEF_RainSensor,	
	&asn_DEF_RegionId,	
	&asn_DEF_RequestedItem,	
	&asn_DEF_RequestID,	
	&asn_DEF_RequestImportanceLevel,	
	&asn_DEF_RequestSubRole,	
	&asn_DEF_ResponseType,	
	&asn_DEF_RestrictionAppliesTo,	
	&asn_DEF_RestrictionClassID,	
	&asn_DEF_RoadRegulatorID,	
	&asn_DEF_RoadSegmentID,	
	&asn_DEF_RoadwayCrownAngle,	
	&asn_DEF_RTCM_Revision,	
	&asn_DEF_RTCMmessage,	
	&asn_DEF_Scale_B12,	
	&asn_DEF_SecondOfTime,	
	&asn_DEF_SegmentAttributeLL,	
	&asn_DEF_SegmentAttributeXY,	
	&asn_DEF_SemiMajorAxisAccuracy,	
	&asn_DEF_SemiMajorAxisOrientation,	
	&asn_DEF_SemiMinorAxisAccuracy,	
	&asn_DEF_SignalGroupID,	
	&asn_DEF_SignalReqScheme,	
	&asn_DEF_SignPrority,	
	&asn_DEF_SirenInUse,	
	&asn_DEF_SpeedAdvice,	
	&asn_DEF_SpeedConfidence,	
	&asn_DEF_SpeedLimitType,	
	&asn_DEF_SpeedProfileMeasurement,	
	&asn_DEF_Speed,	
	&asn_DEF_SSPindex,	
	&asn_DEF_StabilityControlStatus,	
	&asn_DEF_StationID,	
	&asn_DEF_SteeringWheelAngleConfidence,	
	&asn_DEF_SteeringWheelAngleRateOfChange,	
	&asn_DEF_SteeringWheelAngle,	
	&asn_DEF_SunSensor,	
	&asn_DEF_TemporaryID,	
	&asn_DEF_TermDistance,	
	&asn_DEF_TermTime,	
	&asn_DEF_ThrottleConfidence,	
	&asn_DEF_ThrottlePosition,	
	&asn_DEF_TimeConfidence,	
	&asn_DEF_TimeIntervalConfidence,	
	&asn_DEF_DSRC_TimeMark,	
	&asn_DEF_TimeOffset,	
	&asn_DEF_TractionControlStatus,	
	&asn_DEF_TrailerMass,	
	&asn_DEF_TransitStatus,	
	&asn_DEF_TransitVehicleOccupancy,	
	&asn_DEF_TransitVehicleStatus,	
	&asn_DEF_TransmissionState,	
	&asn_DEF_TravelerInfoType,	
	&asn_DEF_UniqueMSGID,	
	&asn_DEF_URL_Base,	
	&asn_DEF_URL_Link,	
	&asn_DEF_URL_Short,	
	&asn_DEF_UserSizeAndBehaviour,	
	&asn_DEF_VehicleEventFlags,	
	&asn_DEF_VehicleHeight,	
	&asn_DEF_VehicleLength,	
	&asn_DEF_VehicleMass,	
	&asn_DEF_VehicleStatusDeviceTypeTag,	
	&asn_DEF_VehicleType,	
	&asn_DEF_VehicleWidth,	
	&asn_DEF_Velocity,	
	&asn_DEF_VerticalAccelerationThreshold,	
	&asn_DEF_VerticalAcceleration,	
	&asn_DEF_VertOffset_B07,	
	&asn_DEF_VertOffset_B08,	
	&asn_DEF_VertOffset_B09,	
	&asn_DEF_VertOffset_B10,	
	&asn_DEF_VertOffset_B11,	
	&asn_DEF_VertOffset_B12,	
	&asn_DEF_VINstring,	
	&asn_DEF_WaitOnStopline,	
	&asn_DEF_WiperRate,	
	&asn_DEF_WiperStatus,	
	&asn_DEF_YawRateConfidence,	
	&asn_DEF_YawRate,	
	&asn_DEF_ZoneLength,	
	&asn_DEF_Zoom,	
	/* From module AddGrpC in ../asn/J2735_201603DA.ASN */
	&asn_DEF_AltitudeConfidence,	
	&asn_DEF_AltitudeValue,	
	&asn_DEF_EmissionType,	
	&asn_DEF_Altitude,	
	&asn_DEF_PrioritizationResponse,	
	&asn_DEF_PrioritizationResponseList,	
	&asn_DEF_ConnectionManeuverAssist_addGrpC,	
	&asn_DEF_IntersectionState_addGrpC,	
	&asn_DEF_MapData_addGrpC,	
	&asn_DEF_Position3D_addGrpC,	
	&asn_DEF_RestrictionUserType_addGrpC,	
	&asn_DEF_SignalHeadLocation,	
	&asn_DEF_SignalHeadLocationList,	
	&asn_DEF_VehicleToLanePosition,	
	&asn_DEF_VehicleToLanePositionList,	
	/* From module AddGrpB in ../asn/J2735_201603DA.ASN */
	&asn_DEF_AddGrpB_Angle,	
	&asn_DEF_Day,	
	&asn_DEF_DayOfWeek,	
	&asn_DEF_DegreesLat,	
	&asn_DEF_DegreesLong,	
	&asn_DEF_AddGrpB_Elevation,	
	&asn_DEF_Holiday,	
	&asn_DEF_Hour,	
	&asn_DEF_LatitudeDMS,	
	&asn_DEF_LongitudeDMS,	
	&asn_DEF_MaxTimetoChange,	
	&asn_DEF_MinTimetoChange,	
	&asn_DEF_Minute,	
	&asn_DEF_MinutesAngle,	
	&asn_DEF_Month,	
	&asn_DEF_AddGrpB_MsgCount,	
	&asn_DEF_Second,	
	&asn_DEF_SecondsAngle,	
	&asn_DEF_SummerTime,	
	&asn_DEF_TenthSecond,	
	&asn_DEF_TimeRemaining,	
	&asn_DEF_Year,	
	&asn_DEF_LatitudeDMS2,	
	&asn_DEF_LongitudeDMS2,	
	&asn_DEF_Node_LLdms_48b,	
	&asn_DEF_Node_LLdms_80b,	
	&asn_DEF_LaneDataAttribute_addGrpB,	
	&asn_DEF_MovementEvent_addGrpB,	
	&asn_DEF_NodeOffsetPointXY_addGrpB,	
	&asn_DEF_Position3D_addGrpB,	
	&asn_DEF_AddGrpB_TimeMark,	
	/* From module NTCIP in ../asn/J2735_201603DA.ASN */
	&asn_DEF_EssMobileFriction,	
	&asn_DEF_EssPrecipRate,	
	&asn_DEF_EssPrecipSituation,	
	&asn_DEF_EssPrecipYesNo,	
	&asn_DEF_EssSolarRadiation,	
	/* From module ITIS in ../asn/J2735_201603DA.ASN */
	&asn_DEF_GenericLocations,	
	&asn_DEF_IncidentResponseEquipment,	
	&asn_DEF_ITIStext,	
	&asn_DEF_ResponderGroupAffected,	
	&asn_DEF_VehicleGroupAffected,	
	&asn_DEF_ITIScodesAndText,	
	&asn_DEF_ITIScodes,	
	0
};

