import { makeStyles } from "@material-ui/core";

export default makeStyles((theme) => ({
    basic30: {
    display: "flex",
    verticalAlign: "middle",
    justifyContent: "center",
    alignItems: "center",
    marginTop: "1rem",
    marginLeft: "1rem",
    marginRight: "1rem",
    margihtBottom:"1rem",
    height: "10rem",
    width: "93%",
    fontSize: "4rem",
    borderRadius: "4px",
    boxShadow: "5px 5px 7px #05060e, -5px -5px 7px #131a3a",
    backgroundColor: "#02dba9",
    color: "#fff",
  },
    red30: {
    display: "flex",
    verticalAlign: "middle",
    justifyContent: "center",
    alignItems: "center",
    marginTop: "1rem",
    marginLeft: "1rem",
    marginRight: "1rem",
    margihtBottom:"1rem",
    height: "10rem",
    width: "93%",
    fontSize: "4rem",
    borderRadius: "4px",
    boxShadow: "5px 5px 7px #05060e, -5px -5px 7px #131a3a",
    backgroundColor: "#f54260",
    color: "#fff",
  },
  label: {
    display: "flex",
    position:"relative",
    fontFamily: "Rajdhani, sans-serif",
    fontSize: "1.5rem",
    alignItems: "center",
    justifyContent: "center",
    color:"#fff",
  },
  small_card: {
    backgroundColor: "#0c1024",
    color: "#fff",
    height: "6rem",
    fontSize: "2.5rem",
    marginLeft: "0.5rem",
    marginRight: "0.5rem",
    margihtBottom:"0.5rem",
    display: "flex",
    boxShadow: "5px 5px 7px #05060e, -5px -5px 7px #131a3a",
    verticalAlign: "middle",
    justifyContent: "center",
    alignItems: "center",
  },
}));