import { makeStyles } from "@material-ui/core";

export default makeStyles((theme) => ({
  map: {
    height: "100%",
  },
  basic50: {
    position: "relative",
    marginTop: "1rem",
    marginLeft: "1rem",
    marginRight: "1rem",
    margihtBottom:"1rem",
    height: "15rem",
    width: "93%",
    fontFamily: "Rajdhani, sans-serif",
    fontSize: "15rem",
    borderRadius: "4px",
    boxShadow: "5px 5px 7px #05060e, -5px -5px 7px #131a3a",
    backgroundColor: "#0c1024",
    color: "#fff",
    "&:hover": {
      borderRadius: "4px",
      boxShadow: "5px 5px 7px #05060e, -5px -5px 7px #131a3a",
      backgroundColor: "#0c1024",
      color: "#fff",
    },
  },
  purple50: {
    position: "relative",
    marginTop: "1rem",
    marginLeft: "1rem",
    marginRight: "1rem",
    margihtBottom:"1rem",
    height: "15rem",
    width: "93%",
    fontFamily: "Rajdhani, sans-serif",
    fontSize: "15rem",
    borderRadius: "4px",
    boxShadow: "5px 5px 7px #05060e, -5px -5px 7px #131a3a",
    backgroundColor: "#6569d7",
    color: "#fff",
    "&:hover": {
      borderRadius: "4px",
      boxShadow: "5px 5px 7px #05060e, -5px -5px 7px #131a3a",
      backgroundColor: "#6569d7",
      color: "#fff",
    },
  },
  basic_card: {
    backgroundColor: "#0c1024",
    color: "#fff",
    height: "25rem",
    fontSize: "5rem",
    marginTop: "1rem",
    marginLeft: "1rem",
    marginRight: "1rem",
    margihtBottom:"1rem",
    display: "flex",
    boxShadow: "5px 5px 7px #05060e, -5px -5px 7px #131a3a",
    verticalAlign: "middle",
    justifyContent: "center",
    alignItems: "center",
  },
}));